### ISSUE TITLE
page specific headers

### ISSUE THREAD

**Issue by Krumuvecis** [Krumuvecis/Admiral#26]
# TODO

- normal mode
  - starting page
    - [x] move buttons to body
    - [x] no header
  - play page
    - [x] menu, pause
- dev mode
  - selection page
    - [x] move buttons to body
    - [x] no header
  - page1
    - [x] menu, pause
  - page2
    - [x] same as page1
