### ISSUE TITLE
improve dev pages

### ISSUE THREAD

**Issue by Krumuvecis** [Krumuvecis/Admiral#7]
# TODO

- [x] barokinetics test page
  * created `page1`
  * created new issue #29
- [x] create blank sample page for copying & pasting
  * created `page0_template`
- [x] fix selection page (layout and borders)
  * created new issue #28
- [x] _more test pages e.g. trading, field objects, players etc..._
  * _will have to wait next PR_
  * created new issue #30

**Comment by Krumuvecis** [comment]
done
